spring:
  config:
    activate:
      on-profile: office
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: mamun
    password: mamun
    driver-class-name: oracle.jdbc.OracleDriver